[project]
name = "tyny"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.7",
    "pydantic-settings>=2.7.1",
    "websockets>=14.2",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
]

