[project]
name = "transcription-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.14",
    "modal>=1.0.5",
    "nemo-toolkit[asr]>=2.3.2",
]
